Changed yaml files

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,37 +1,85 @@
 name: Cucumber CI
-
-on:
-  push:
-  pull_request:
-    branches:
-      - main
-
+on: [push]
 jobs:
   build:
-    name: 'Build'
+    name: Build
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - name: Cache local Maven repository
-        uses: actions/cache@v3
-        with:
-          path: ~/.m2/repository
-          key: build-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
-          restore-keys: |
-            build-${{ runner.os }}-maven-
-      - uses:
-          AdoptOpenJDK/install-jdk@v1
-        with:
-          version: '11'
-      - name: test maven
-        run: |
-          cd maven
-          ./mvnw test -Dmaven.test.failure.ignore
-      - run: grep -q "The step 'I wait 1 hour' and 1 other step(s) are undefined." maven/target/surefire-reports/io.cucumber.skeleton.RunCucumberTest.txt || ( echo "mvn test didn't fail as expected" && false )
-      - name: test gradle
-        run: |
-          cd gradle
-          ./gradlew test || true
-      - run: grep -q "The step 'I wait 1 hour' and 1 other step(s) are undefined." gradle/build/reports/tests/test/classes/io.cucumber.skeleton.RunCucumberTest.html  || ( echo "gradle test didn't fail as expected" && false )
-      - name: compare gradle and maven sources
-        run: diff gradle/src maven/src
+    - uses: actions/setup-python@v2
+      with:
+        python-version: '3.10'
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install pandas
+        pip install numpy
+    - run: sudo apt update
+    - run: sudo apt install inotify-tools
+    - run: inotifywait -mr /home/runner/work/cucumber-java-skeleton/cucumber-java-skeleton/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
+    - run: touch starting_build_uses-checkout_12
+    - run: rm starting_build_uses-checkout_12
+    - uses: actions/checkout@v3
+    - run: touch starting_build_CachelocalMavenrepository_13
+    - run: rm starting_build_CachelocalMavenrepository_13
+    - name: Cache local Maven repository
+      uses: actions/cache@v3
+      with:
+        path: ~/.m2/repository
+        key: build-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+        restore-keys: 'build-${{ runner.os }}-maven-
+
+          '
+    - run: touch starting_build_uses-install-jdk_21
+    - run: rm starting_build_uses-install-jdk_21
+    - uses: AdoptOpenJDK/install-jdk@v1
+      with:
+        version: '11'
+    - run: touch starting_build_testmaven_24
+    - run: rm starting_build_testmaven_24
+    - name: test maven
+      run: 'cd maven
+
+        ./mvnw test -Dmaven.test.failure.ignore
+
+        '
+    - run: touch starting_build_grepqThestepIwait1hourand1otherstepsareundefinedmaventargetsurefirereportsiocucumberskeletonRunCucumberTesttxt_30
+    - run: rm starting_build_grepqThestepIwait1hourand1otherstepsareundefinedmaventargetsurefirereportsiocucumberskeletonRunCucumberTesttxt_30
+    - run: grep -q "The step 'I wait 1 hour' and 1 other step(s) are undefined." maven/target/surefire-reports/io.cucumber.skeleton.RunCucumberTest.txt
+        || ( echo "mvn test didn't fail as expected" && false )
+    - run: touch starting_build_testgradle_32
+    - run: rm starting_build_testgradle_32
+    - name: test gradle
+      run: 'cd gradle
+
+        ./gradlew test || true
+
+        '
+    - run: touch starting_build_grepqThestepIwait1hourand1otherstepsareundefinedgradlebuildreportsteststestclassesiocucumberskeletonRunCucumberTesthtml_38
+    - run: rm starting_build_grepqThestepIwait1hourand1otherstepsareundefinedgradlebuildreportsteststestclassesiocucumberskeletonRunCucumberTesthtml_38
+    - run: grep -q "The step 'I wait 1 hour' and 1 other step(s) are undefined." gradle/build/reports/tests/test/classes/io.cucumber.skeleton.RunCucumberTest.html  ||
+        ( echo "gradle test didn't fail as expected" && false )
+    - run: touch starting_build_comparegradleandmavensources_40
+    - run: rm starting_build_comparegradleandmavensources_40
+    - name: compare gradle and maven sources
+      run: diff gradle/src maven/src
+    - run: touch starting_finished_finished_8979874
+      if: always()
+    - run: rm starting_finished_finished_8979874
+      if: always()
+    - name: Execute py script # run file
+      if: always()
+      run: |
+        python .github/workflows/script.py
+    - name: Pushes analysis to another repository
+      if: always()
+      id: push_directory
+      uses: cpina/github-action-push-to-another-repository@main
+      env:
+        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
+      with:
+        source-directory: 'optimizing-ci-builds-ci-analysis'
+        destination-github-username: 'UT-SE-Research'
+        destination-repository-name: 'ci-analyzes'
+        target-branch: '1675906320'
+        target-directory: 'cucumber-java-skeleton/.github/workflows/build/build'
+
